import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { getArchiveFeatures, getHistoryBrowseArticles } from '../lib/content/archive.ts';

test('approved factual matches and player articles enter their respective History browsers', () => {
  assert.deepEqual(getHistoryBrowseArticles('matches').map(a => a.slug).sort(), [
    'bournemouth-liverpool-2026-09-20',
    'newcastle-liverpool-2026-08-23',
    'liverpool-tottenham-2026-09-15',
    'liverpool-nottingham-forest-2026-08-29',
    'ipswich-liverpool-2026-09-04',
    'liverpool-atletico-madrid-2026-09-09',
    'liverpool-fulham-2026-09-12',
    'liverpool-everton-1972-cormack-winner',
    'liverpool-newcastle-1972-five-goal-win',
    'liverpool-birmingham-1972-comeback',
    'liverpool-dynamo-berlin-1972-uefa-cup',
    'everton-liverpool-1973-hughes-double',
    'liverpool-tottenham-1973-lindsay-semi-final',
    'liverpool-leeds-1973-cormack-keegan',
    'tottenham-liverpool-1973-heighway-away-goal',
    'liverpool-gladbach-1973-keegan-toshack-final',
    'gladbach-liverpool-1973-first-european-trophy',
    'red-star-liverpool-1973-lawler-away-goal',
    'arsenal-liverpool-1973-first-away-win',
    'liverpool-red-star-1973-european-lesson',
    'everton-liverpool-1973-alan-waddle',
    'liverpool-manchester-united-1973-ten-home-wins',
    'alonso-own-half-newcastle-2006',
    'anfield-first-european-match-reykjavik-1964',
    'forshaw-hat-trick-manchester-united-1925',
    'fowler-scoring-debut-fulham-1993',
    'henderson-chelsea-winner-2016',
    'leeds-liverpool-1971-early-winner',
    'liverpool-bayern-1971-alun-evans',
    'tottenham-liverpool-1971-heighway-clemence',
    'liverpool-everton-1971-brian-hall',
    'liverpool-arsenal-1971-fa-cup-final',
    'liverpool-arsenal-1971-ian-ross',
    'liverpool-derby-1971-jack-whitham',
    'liverpool-everton-1972-four-goal-derby',
    'liverpool-newcastle-1972-five-goals',
    'manchester-united-liverpool-1972-thompson-debut',
    'derby-liverpool-1972-mcgovern-title-race',
    'liverpool-manchester-city-1972-opening-day',
    'liverpool-sheffield-united-1972-five-goals',
    'leeds-liverpool-1972-phil-boersma',
    'liverpool-arsenal-1971-toshack-smith',
    'liverpool-everton-comeback-1970',
    'liverpool-monaco-champions-league-2004',
    'liverpool-stromsgodset-record-win-1974',
    'mcmahon-four-fulham-ten-goals-1986',
    'saunders-four-kuusysi-european-return-1991',
    'steve-nicol-hat-trick-newcastle-1987',
    'torres-babel-six-goals-hull-2009',
    'torres-first-hat-trick-reading-2007',
    'whelan-wembley-final-tottenham-1982',
    'bristol-city-liverpool-1974-toshack-cup-quarter-final',
    'liverpool-leicester-1974-semi-final-replay',
    'liverpool-newcastle-1974-fa-cup-final',
    'tottenham-liverpool-1974-shankly-final-league-match',
    'liverpool-leeds-1974-charity-shield',
    'liverpool-tottenham-1974-boersma-hat-trick',
    'liverpool-manchester-city-1974-boxing-day',
    'liverpool-ipswich-1975-toshack-double',
    'liverpool-newcastle-1975-toshack-mcdermott',
    'bill-shankly-testimonial-anfield-1975',
    'leeds-liverpool-1975-callaghan-double',
    'liverpool-hibernian-1975-toshack-headers',
    'tottenham-liverpool-1975-four-scorers',
    'liverpool-ipswich-1976-three-equalisers',
    'barcelona-liverpool-1976-toshack-advantage',
    'liverpool-everton-1976-fairclough-derby-winner',
    'liverpool-barcelona-1976-thompson-semi-final',
    'liverpool-stoke-1976-eight-goal-easter',
    'manchester-city-liverpool-1976-fairclough-double',
    'liverpool-brugge-1976-anfield-final-comeback',
    'wolves-liverpool-1976-title-at-molineux',
    'brugge-liverpool-1976-uefa-cup-double',
    'liverpool-southampton-1976-toshack-charity-shield',
    'derby-liverpool-1976-keegan-comeback-winner',
    'saint-etienne-liverpool-1977-first-leg-deficit',
    'liverpool-saint-etienne-1977-fairclough-winner',
    'liverpool-leeds-1977-fairclough-league-victory',
    'zurich-liverpool-1977-neal-first-leg-win',
    'liverpool-zurich-1977-first-european-cup-final',
    'liverpool-everton-1977-semi-final-draw',
    'liverpool-everton-1977-replay-wembley',
    'liverpool-ipswich-1977-kennedy-keegan',
    'liverpool-west-ham-1977-tenth-title',
    'liverpool-manchester-united-1977-fa-cup-final',
    'liverpool-gladbach-1977-first-european-cup',
    'middlesbrough-liverpool-1977-dalglish-league-debut',
    'liverpool-west-bromwich-albion-1977-dalglish-third-goal',
    'liverpool-dynamo-dresden-1977-five-goal-defence',
    'hamburg-liverpool-1977-fairclough-super-cup',
    'liverpool-hamburg-1977-super-cup',
    'liverpool-arsenal-1978-league-cup-semi-final',
    'benfica-liverpool-1978-hughes-winner',
    'liverpool-benfica-1978-european-cup-semi-final',
    'liverpool-nottingham-forest-1978-wembley-draw',
    'liverpool-nottingham-forest-1978-european-cup-exit',
    'liverpool-nottingham-forest-1978-league-cup-replay',
    'liverpool-gladbach-1978-semi-final',
    'liverpool-brugge-1978-european-cup-final',
    'ipswich-liverpool-1978-dalglish-double',
    'manchester-city-liverpool-1978-souness-double',
    'nottingham-forest-liverpool-1978-first-leg',
    'liverpool-derby-county-1978-five-goals',
    'manchester-united-liverpool-1978-boxing-day',
    'liverpool-norwich-1979-six-goals',
    'liverpool-aston-villa-1979-eleventh-title',
    'leeds-liverpool-1979-record-points',
    'liverpool-arsenal-1979-charity-shield',
    'liverpool-tranmere-1979-second-half',
    'liverpool-oulu-1980-ten-goals',
    'dinamo-tbilisi-liverpool-1979-european-exit',
    'manchester-city-liverpool-1979-dalglish-double',
    'liverpool-manchester-united-1979-boxing-day',
    'everton-liverpool-1980-goodison-derby',
    'tottenham-liverpool-1980-mcdermott-volley',
    'liverpool-arsenal-1980-hillsborough-stalemate',
    'liverpool-arsenal-1980-dalglish-second-replay',
    'liverpool-arsenal-1980-talbot-third-replay',
    'liverpool-aston-villa-1980-cohen-title',
    'liverpool-west-ham-1980-mcdermott-shield',
    'aberdeen-liverpool-1980-mcdermott-chip',
    'liverpool-aberdeen-1980-quarter-finals',
    'liverpool-cska-sofia-1981-souness-treble',
    'liverpool-west-ham-1981-final-draw',
    'liverpool-oulu-1981-rush-first-goal',
    'liverpool-west-ham-1981-first-league-cup',
    'liverpool-bayern-1981-anfield-draw',
    'bayern-liverpool-1981-ray-kennedy-away-goal',
    'liverpool-real-madrid-1981-third-european-cup',
    'liverpool-az-1981-hansen-late-winner',
    'liverpool-everton-1981-dalglish-double',
    'flamengo-liverpool-1981-tokyo-defeat',
    'liverpool-manchester-city-1981-boxing-day-defeat',
    'everton-liverpool-1982-midfield-goals',
    'manchester-united-liverpool-1982-johnston-winner',
    'manchester-city-liverpool-1982-five-goals',
    'tottenham-liverpool-1982-dalglish-recovery',
    'liverpool-nottingham-forest-1982-late-recovery',
    'liverpool-luton-1982-three-goalkeepers',
    'everton-liverpool-1982-rush-four',
    'liverpool-manchester-city-1982-dalglish-hat-trick',
    'liverpool-brighton-1983-case-cup-winner',
    'widzew-liverpool-1983-two-goal-deficit',
    'liverpool-widzew-1983-victory-elimination',
    'liverpool-manchester-united-1983-whelan-final',
    'liverpool-aston-villa-1983-paisley-anfield-farewell',
    'arsenal-liverpool-1983-dalglish-finish',
    'liverpool-luton-1983-rush-five',
    'athletic-bilbao-liverpool-1983-rush-header',
    'liverpool-everton-1983-derby-lead',
    'liverpool-walsall-1984-semi-final-draw',
    'benfica-liverpool-1984-dalglish-three-assists',
    'liverpool-everton-1984-wembley-draw',
    'liverpool-everton-1984-souness-replay-winner',
    'liverpool-west-ham-1984-four-before-half-hour',
    'liverpool-dinamo-1984-lee-header',
    'dinamo-liverpool-1984-rush-double',
    'liverpool-roma-1984-kennedy-penalty',
    'liverpool-everton-1984-charity-shield-own-goal',
    'liverpool-everton-1984-sharp-volley',
    'liverpool-benfica-1984-rush-hat-trick',
    'benfica-liverpool-1984-quarter-final-survival',
    'liverpool-austria-vienna-1985-walsh-double',
    'liverpool-panathinaikos-1985-rush-double',
    'liverpool-manchester-united-1985-two-late-equalisers',
    'liverpool-manchester-united-1985-replay-defeat',
    'liverpool-arsenal-1985-dalglish-first-competitive-match',
    'liverpool-tottenham-1985-molby-two-penalties',
    'liverpool-manchester-united-1985-molby-turnaround',
    'liverpool-everton-1986-eight-points-behind',
    'liverpool-qpr-1986-dalglish-returns',
    'watford-liverpool-1986-rush-replay-winner',
    'liverpool-oxford-1986-dalglish-creates-six-goal-win',
    'liverpool-southampton-1986-rush-extra-time-double',
    'chelsea-liverpool-1986-dalglish-title-winner',
    'liverpool-everton-1986-rush-double-wembley',
    'liverpool-everton-1986-shared-charity-shield',
    'liverpool-everton-1986-super-cup-first-leg',
    'everton-liverpool-1986-super-cup-rush-hat-trick',
    'liverpool-norwich-1986-walsh-hat-trick',
    'liverpool-leicester-1987-rush-hat-trick',
    'liverpool-arsenal-1987-nicholas-league-cup-final',
    'liverpool-everton-1987-rush-equals-dean',
    'arsenal-liverpool-1987-barnes-beardsley-debuts',
    'liverpool-qpr-1987-barnes-takes-liverpool-top',
    'liverpool-everton-1987-barnes-creates-derby-win',
    'liverpool-newcastle-1987-aldridge-double',
    'liverpool-coventry-1988-beardsley-new-year-double',
    'everton-liverpool-1988-houghton-cup-header',
    'everton-liverpool-1988-unbeaten-start-ends',
    'liverpool-manchester-united-1988-two-goal-lead-lost',
    'liverpool-nottingham-forest-1988-aldridge-semi-final-double',
    'liverpool-nottingham-forest-1988-five-at-anfield',
    'liverpool-wimbledon-1988-fa-cup-final-defeat',
    'liverpool-wimbledon-1988-aldridge-shield-double',
    'liverpool-man-united-1988-molby-penalty',
    'liverpool-arsenal-1988-aldridge-second-replay',
    'man-united-liverpool-1989-seven-minutes',
    'everton-liverpool-1989-return-at-goodison',
    'liverpool-nottingham-forest-1989-rescheduled-semi-final',
    'liverpool-everton-1989-rush-extra-time-double',
    'liverpool-west-ham-1989-four-second-half-goals',
    'liverpool-arsenal-1989-thomas-title-decider',
    'everton-liverpool-1989-rush-double-takes-top-spot',
    'liverpool-arsenal-1989-barnes-free-kick',
    'chelsea-liverpool-1989-five-at-stamford-bridge',
    'liverpool-swansea-1990-rush-replay-hat-trick',
    'liverpool-everton-1990-barnes-beardsley-derby-double',
    'palace-liverpool-1990-semi-final',
    'liverpool-qpr-1990-eighteenth-title',
    'coventry-liverpool-1990-barnes-hat-trick',
    'liverpool-manchester-united-1990-beardsley-hat-trick',
    'everton-liverpool-1990-opening-streak',
    'everton-liverpool-1991-four-four',
    'liverpool-arsenal-1991-title-race',
    'derby-liverpool-1991-seven-goals',
    'leeds-liverpool-1991-five-four',
    'liverpool-9-crystal-palace-0',
    'liverpools-manager-scored-after-21-seconds-at-goodison',
  ].sort());
  assert.deepEqual(getHistoryBrowseArticles('players').map(a => a.slug), ['john-barnes-1987', 'phil-thompson']);
  assert.equal(getArchiveFeatures().filter(a => a.editorialMode !== 'factual').length, 2);
});

test('future player content needs explicit approval and player type; shared player tags do not create profiles', () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'history-browse-'));
  try {
    fs.cpSync('content', path.join(root, 'content'), { recursive: true });
    const filename = path.join(root, 'content/archive/liverpool/phil-thompson.md');
    const original = fs.readFileSync(filename, 'utf8').replace(/^editorialMode:.*\n/m, '');
    fs.writeFileSync(filename, original.replace('articleType: "player"', 'articleType: "player"\neditorialMode: "factual"'));
    assert.deepEqual(getHistoryBrowseArticles('players', root).map(a => a.slug), ['john-barnes-1987', 'phil-thompson']);
    fs.writeFileSync(filename, original.replace('articleType: "player"', 'articleType: "manager"\neditorialMode: "factual"'));
    assert.deepEqual(getHistoryBrowseArticles('players', root).map(a => a.slug), ['john-barnes-1987']);
    fs.writeFileSync(filename, original.replace('articleType: "player"', 'articleType: "player"\neditorialMode: "opinion"'));
    assert.deepEqual(getHistoryBrowseArticles('players', root).map(a => a.slug), ['john-barnes-1987']);
    fs.writeFileSync(filename, original.replace('articleType: "player"', 'articleType: "player"\neditorialMode: "automatic"'));
    assert.throws(() => getArchiveFeatures(root), /phil-thompson/);
  } finally { fs.rmSync(root, { recursive: true, force: true }); }
});

test('player biographies sort by the canonical subject first name, independently of title and publication date', () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'history-player-order-'));
  try {
    fs.cpSync('content', path.join(root, 'content'), { recursive: true });
    for (const slug of ['phil-thompson', 'john-barnes-1987']) {
      const filename = path.join(root, 'content/archive/liverpool', `${slug}.md`);
      const original = fs.readFileSync(filename, 'utf8').replace(/^editorialMode:.*\n/m, '');
      fs.writeFileSync(filename, original.replace('articleType: "player"', 'articleType: "player"\neditorialMode: "factual"')
        .replace(/^title:.*$/m, `title: "${slug === 'phil-thompson' ? 'A captain' : 'Z winger'}"`));
    }
    // Put first-name order in conflict with surname order.
    const entitiesPath = path.join(root, 'content/history/liverpool/entities.json');
    const entities = JSON.parse(fs.readFileSync(entitiesPath, 'utf8'));
    entities.find(entity => entity.id === 'phil-thompson').label = 'Alan Thompson';
    fs.writeFileSync(entitiesPath, JSON.stringify(entities));
    assert.deepEqual(getHistoryBrowseArticles('players', root).map(a => a.slug), ['phil-thompson', 'john-barnes-1987']);
  } finally { fs.rmSync(root, { recursive: true, force: true }); }
});
